### PR TITLE
Add TypeScript type definitions (in progress)

### PR DESCRIPTION
**Pull request by Kroisse**
*Issue #, if available:* #14 

*Description of changes:*

Adds type definitions of "public" items of this library, for TypeScript compiler.

This was derived from my private work, so lots of items are omitted or incomplete.

*Todo:*

 - [ ] Add type inference tests using [dtslint](https://github.com/Microsoft/dtslint)
   - See also: https://hackernoon.com/testing-types-an-introduction-to-dtslint-b178f9b18ac8
 - [ ] Add `XRaySegment` field in the parameter of all methods of capturing clients, for manual mode.
 - [ ] Add complete set of type definitions of `aws-xray-sdk-core`
 - [ ] Add a type definition of `aws-xray-sdk-express`
 - [ ] Add a type definition of `aws-xray-sdk-mysql`
 - [ ] Add a type definition of `aws-xray-sdk-postgres`
 - [ ] Add a type definition of `aws-xray-sdk-restify`
 - [ ] Add a type definition of `aws-xray-sdk`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chrisradek** [comment]
@Kroisse 
Thank you for getting this PR kicked off! This one will take me a little while to review, since ideally we will only want to expose types for APIs we consider public-facing.

One thing I noticed was that you placed the type definitions in a separate `types` folder within their respective packages. Can you place the type definitions alongside the JavaScript source instead? That will mimic what the TypeScript compiler does when it compiles `ts` files, and make the `tsconfig.json` simpler as well. It should also make the types more easily accessible for contributors of the library too.

**Comment by duro** [comment]
Here to cheer this effort on 🎉🎉🎉

**Comment by Charliekenney23** [comment]
@Kroisse Is this actually still in progress? If not, I'd be happy to help

**Comment by saferrer** [comment]
@Kroisse is this still in progress?

**Comment by esilkensen** [comment]
It looked like this PR might be abandoned, so I used it as a jumping off point and have just opened #207 which I think is ready for review! 🚀

**Pull request closed without merging**
