### PR TITLE
support callback style queries in aws-xray-sdk-postgres

### PR DESCRIPTION
**Pull request by jafl**
*Issue #, if available:*

#34

*Description of changes:*

Add support for callback style queries in aws-xray-sdk-postgres.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ebaioni** [comment]
looking forward to this. Thanks for taking the time to look into it

**Comment by chrisradek** [comment]
@jafl 
Sorry for the delayed response. Thank you for digging into #34 and submitting a solution! Does this have any impact when using promises or when using pg 6.x?

**Comment by jafl** [comment]
@chrisradek - this PR shouldn't affect the promises API - that was already merged in a previous PR.  I haven't tested pg 6.x.  If you're using it, try it and let me know :)

**Comment by ebaioni** [comment]
Hi everyone, thanks for the continuous efforts put towards this repo.
Would it be possible to integrate this change?

**Comment by chrisradek** [comment]
@jafl 
Sorry for the delay in reviewing. Playing catch-up after the holidays! I'm testing your changes today and will report back shortly!

**Comment by chrisradek** [comment]
@jafl 
Thank you for your contribution! Merging!

**Pull request merged**
