### PR TITLE
Add support for koa

### PR DESCRIPTION
**Pull request by tuananh**
- This PR adds supports for koa framework.
- Based on express middleware.
- Tests included.

### CODE REVIEW

**Comment by tuananh** [comment]
@haotianw465 @jamesiri can someone take a look at this?

**Comment by willarmiros** [comment]
Hi @tuananh, 

Sorry we weren't able to follow up on this due to SDK limitations. But with the added support for `async/await` in v3.0.0 of the SDK via `cls-hooked`, we should be able to support Koa now. Would you be interested in reopening this PR and making some necessary updates?

**Comment by jgcmarins** [comment]
friendly remind for @tuananh

**Comment by tuananh** [comment]
Sorry, I dont have the resource to work on this at the moment.

**Pull request closed without merging**
