### PR TITLE
Return response when using captureFunc and captureAsyncFunc

### PR DESCRIPTION
**Pull request by aldex32**
Hi guys,

I have created this PR in order to get the function result when capturing functions and async functions.
Let me know if this make sense to you.

Cheers,
Aldo

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awssandra** [comment]
Hi aldex32,

Thanks for the PR. Can you tell me a bit about the use case of this change? This would also require an edit to the API documentation/readme in respect to the functions behavior.

Thanks!
Sandra

**Comment by aldex32** [comment]
Hi @awssandra ,

the use case would be when the user needs to trace a function which returns a value.
For instance I would like sub segment by wrapping an external library which does an http call and returns a result.
```
const getInfo = () => externalLibrary.getInfo();
const response = await AWSXRay.captureAsyncFunc('getInfo', getInfo, AWSXRay.getSegment())
```
If that makes sense for you then I can modify the API documentation.

Let me know,
Aldo

**Comment by aldex32** [comment]
Hi @awssandra,

I didn't hear anymore from you. Do you agree with this PR?

**Comment by williamhoyle** [comment]
@aldex32, your async example won't work as expected. You'd have to wrap the external function to close the segment:

```javascript
const getInfo = segment => externalLibrary
  .getInfo()
  .then(res => {
    segment.close();
    return res;
  })
  .catch(e => {
    segment.close(e);
    throw e;
  });
```

**Comment by aldex32** [comment]
Hi @williamhoyle, 
I think you are right, but you don't need to close the segment in the catch, since it will be eventually closed by *captureAsyncFunc()*. So it should be something like this:
```JavaScript
const getInfo = async (segment) => {
  const result = await externalLibrary.getInfo();

  segment.close();

  return result;
}

const response = await AWSXRay.captureAsyncFunc('getInfo', getInfo, AWSXRay.getSegment());
```

**Comment by williamhoyle** [comment]
@aldex32 eventually, but not with the correct timestamp. 

This is a good  PR without the async stuff. `captureFunc` can return a result without  side affects,  `captureAsyncFunc` not so much. 

Just back the async stuff out and I think you've got a shot.

**Comment by haotianw465** [comment]
Hi @williamhoyle , what do you mean by there are side effects on `captureAsyncFun`? It looks to me the timestamp is accurate on both success and exception.

**Comment by williamhoyle** [comment]
> Hi @williamhoyle , what do you mean by there are side effects on `captureAsyncFun`? It looks to me the timestamp is accurate on both success and exception.

Sorry, my comment was poorly worded. I was referring to @aldex32's example, not the current implementation of `captureAsyncFun`.

**Comment by haotianw465** [comment]
Thank you for your contribution. I have merged the change to master.

**Comment by aldex32** [comment]
Thanks for merging it!

**Pull request merged**
