### PR TITLE
refs #294, add support for AWS SDK v3

### PR DESCRIPTION
**Pull request by monken**
#294

* add support for AWS SDK v3

I used typescript for the actual patcher because it makes the code safer and I wanted to make sure that types are maintained when using the XRay patcher. I included the complied JavaScript code as well so that tests can be run without adding more typescript flavor to the project.

There is no captureAWS for now and I also haven't looked at manual mode much because I'm unsure about how to pass in the xray params in a type-safe way.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by monken** [comment]
@willarmiros sorry I messed up and deleted the source branch, this replaces #298

**Comment by monken** [comment]
@willarmiros for some reason `@aws-sdk/service-error-classification` doesn't get installed before the tests are executed. Could you please have a look? Do I need to add it to the root package.json file instead?

**Comment by willarmiros** [comment]
@monken we recently committed a `package-lock.json` to our repo and use it for CI tests. You'll probably need to run a `npx lerna bootstrap --hoist` from the root of the repo to generate it and include the new deps.

**Comment by emdgroup-admin** [comment]
@willarmiros thanks! Looks much better now!

**Comment by monken** [comment]
@willarmiros looks much better now, thanks!

**Review by willarmiros — APPROVED** [review]
Approving because the last comment isn't really blocking, but would be nice to have to avoid confusion in the future. Nice work @monken!

**Comment by willarmiros** [comment]
@monken any update on these final couple changes?

**Comment by monken** [comment]
Oh I thought we were done. Sorry about this. I'll push the changes today.

**Review by willarmiros — APPROVED** [review]
Tests are updated and passing, merging time!

**Pull request merged**
